version: '3.7'

services:
    app:
        build: proxy
        restart: ${RESTART:-no}
        ports: 
            - "${HOST_PORT}80"
        volumes: 
            - ./app:/app
        networks:
            - nginx-gateway

networks:
    nginx-gateway:
        external:
            name: nginx-gateway